services:

  api:
    build: 
      context: .
      dockerfile: api/Dockerfile.api
    environment:
      - DEBUG=${DEBUG}
      - UPDATE_PASSWORD=${UPDATE_PASSWORD}
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./logs:/logs:rw
      - ./data:/data:rw
    networks:
      - seg_network

  bot:
    build: 
      context: .
      dockerfile: bot/Dockerfile.bot
    environment:
      - DEBUG=${DEBUG}
      - BOT_TOKEN=${BOT_TOKEN}
      - WS_SERVER_URI=${WS_SERVER_URI}
      - UPDATE_PASSWORD=${UPDATE_PASSWORD}
      - ADMIN_IDS=${ADMIN_IDS}
    restart: unless-stopped
    volumes:
      - ./logs:/logs:rw
      - ./data:/data:rw
    depends_on:
      - api
    networks:
      - seg_network
  
  web:
    build:
      context: .
      dockerfile: web/Dockerfile.web
    ports:
      - "5173:5173"
      - "443:443"
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_DEBUG: ${DEBUG}
      VITE_AUTHORS: ${VITE_AUTHORS}


networks:
  seg_network:
    driver: bridge